#EchoCmd.conf - Control output of echo command.

# This file will allow for use of echo, cecho, and printf, with other options available, such as centerecho.

EchoCmd="cecho" # Can be 'echo', 'cecho', 'printf', or 'printf \n'.
  
