#
# Define Files To Load w/ Config Names. #
#
BashAlias_LoaderFile="$BRCDPath/01_bash-aliases.brcd"
Cecho_LoaderFile="$BRCDPath/10_cecho.brcd"
BLING_LoaderFile="$BRCDPath/20_BLING_Loader.brcd"
Powerline_LoaderFile="$BRCDPath/80_powerline.brcd"
FastFetch_LoaderFile="$BRCDPath/90_fastfetch.brcd"
Tmux_LoaderFile="$BRCDPath/97_tmux.brcd"

# Configure Which Items To Load. #
#
EnableLoader_BashAlias="1"
EnableLoader_Cecho="1"
EnableLoader_BLING="1"
EnableLoader_Powerline="1"
EnableLoader_FastFetch="1"
EnableLoader_Tmux="1"

# Run PS1ConfigTool if Enabled.
RunPS1ConfigTool="0" # Needs Code To Use!

