# INI Config File for BRCD #
#
[Bash_Aliases]
LoaderFile="$BRCDPath/01_bash-aliases.brcd"
Enabled=1

[Cecho]
Cecho_LoaderFile="$BRCDPath/10_cecho.brcd"
Enabled=1

[BLING]
BLING_LoaderFile="$BRCDPath/20_BLING_Loader.brcd"
Enabled=1

[Powerline]
Powerline_LoaderFile="$BRCDPath/80_powerline.brcd"
Enabled=1

[FastFetch]
FastFetch_LoaderFile="$BRCDPath/90_fastfetch.brcd"
Enabled=1

[Tmux]
Tmux_LoaderFile="$BRCDPath/97_tmux.brcd"
Enabled=1

