# INI Config File for BRCD #
#

# ----- Folder Paths ----- #
[BRCD-FolderPaths]
BRCDPath="/etc/bashrc.d"
BLINGPath="/etc/BLING/functions"
PS1ConfigToolPath="/etc/PS1ConfigTool" # New For v6

# ----- File Names ----- #
[BRCD-FileNames]
PreLoader_FileName="AdvPreLoader.sh"
Cecho_FileName="Cecho.bfunc"

# Colors for Cecho-like output
COLORS_FILE="AdvPreLoader_Colors.conf"  # Will eventually be replaced by Cecho.


